name: Fly Deploy
on:
  push:
    branches:
      - test
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl launch --auto-confirm --region lax --no-deploy --name art-expert-naik
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLYIO_TOKEN }}