name: Fly Deploy
on:
  push:
    branches:
      - test

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
#       - run: flyctl launch --auto-confirm --access-token fo1_FhYq4HK3XDly-8E78v-PC4gEoLyH0RoQ0vtrXI80x5A --region lax --no-deploy --name art-expert-naik
      - run: flyctl launch --auto-confirm --path fastapi-deployment/dockerdir2  --region lax --no-deploy --name art-expert-naik
      - run: flyctl deploy --remote-only
